# permissions for end users to edit kodespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kodespace-editor-role
rules:
- apiGroups:
  - kode.swiftdiaries.com
  resources:
  - kodespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.swiftdiaries.com
  resources:
  - kodespaces/status
  verbs:
  - get
